### ISSUE TITLE
problem with uni1-student mapping

### ISSUE THREAD

**Issue by bagindokemas** [ontop/ontop-tutorial#1]
Hi Ontop Team,

I found an error when I tried to create the following mapping based on the tutorial: 
mappingId	uni1-student
target		:uni1/student/{s_id} a :Student ; foaf:firstName {first_name}^^xsd:string ; foaf:lastName {last_name}^^xsd:string . 
source		SELECT * FROM "uni1-student"

Protege reported that nullfirstName and nulllastName are predicates which are unknown by the ontology (please see the attached picture). FYI, I used Protege 5.2.0 and Ontop 1.18.1.

![mapping Error](https://user-images.githubusercontent.com/6532739/63034977-35591f00-beb2-11e9-81eb-74c4bdfd3c45.png)

**Comment by ghxiao** [comment]
1. please use the latest version of Ontop v3-beta-2. 

2. The error message shows that the properties (foaf:firstname and foaf:lastname) are not declared in the ontology and therefore cannot be used in the mapping. So you need to add them to the ontology, or use directly the ontology we have prepared in the repository.
